version: '2'
services:
  redis-cache:
    container_name: books-directory-cache
    image: redis/redis-stack-server:latest
    volumes:
      - ~/books-directory-redis-cache:/data/cache
    ports:
      - 6379:6379
    networks:
      - my-network
    restart: 'no'
  mongo-db:
    container_name: books-directory-db
    image: mongo:latest
    volumes:
      - ~/books-directory-mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
    restart: 'no'
  books-directory:
    depends_on:
      - mongo-db
      - redis-cache
    container_name: books-directory-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./src/config/.env.development
    environment:
      WAIT_HOSTS: mongo-db:27017,redis-cache:6379
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    links:
      - mongo-db
      - redis-cache
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
