version: '2'
services:
  db:
    container_name: books-directory-db
    image: mongo:latest
    volumes:
      - ~/books-directory-mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
    restart: 'no'
  books-directory:
    depends_on:
      - db
    container_name: books-directory-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./src/config/.env.development
    environment:
      WAIT_HOSTS: db:27017
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    links:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
